version: '3.8'

networks:
  asap:
    driver: bridge

services:
  db:
    image: mysql:5.7
    container_name: asap-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}     
      - MYSQL_DATABASE=${DB_NAME}          
      - MYSQL_USER=${DB_USER}              
      - MYSQL_PASSWORD=${DB_PASS}          
    ports:
      - ${DB_PORT}:3306                    
    networks:
      - asap
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
